services:
  - type: web
    name: jerseypremierleague-api
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: JWT_SECRET
        value: b15c2dd31bdf8c2ff375f0b99fbca875f63ee7151173fb71d76faf186a29470c
      - key: FRONTEND_URL
        value: https://jerseypremierleague-web.onrender.com
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_FROM
        value: rahulelsharaawy@gmail.com
      - key: EMAIL_APP_PASSWORD
        value: jubqfncmzhjczkrs
      - key: GOOGLE_CLIENT_ID
        value: 1017396303090-5no4v1s8j7hdl158cktde84bapjc9u2q.apps.googleusercontent.com
      - key: ADMIN_EMAILS
        value: jerseypremierleaguee@gmail.com,jpl_admin2@gmail.com,jpl_admin3@gmail.com,jpl_admin4@gmail.com
